name: Ruby

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}

      - name: Bundler Install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: RuboCop
        run: bundle exec rubocop
